# Generated by Django 3.0.4 on 2020-04-24 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200424_1403'),
        ('activities', '0002_auto_20200423_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='rq_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Request'),
        ),
    ]
