# Generated by Django 3.0.4 on 2020-04-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20200424_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='picture_path',
            field=models.FileField(upload_to='activities'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture_path',
            field=models.FileField(upload_to='album'),
        ),
    ]
