# Generated by Django 3.0.4 on 2020-04-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20200426_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='album_name',
        ),
    ]
