# Generated by Django 3.0.4 on 2020-04-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Audience_suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('Ca', 'camera'), ('Le', 'lens'), ('Si', 'light'), ('Ot', 'other')], max_length=2)),
                ('equipment_detail', models.TextField()),
                ('equipment_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member_suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_title', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('picture_path', models.URLField(max_length=500, null=True)),
                ('detail', models.TextField()),
                ('request_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Date_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('finish_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
