# Generated by Django 3.0.4 on 2020-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200416_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_account',
            name='audience',
            field=models.BooleanField(default=True),
        ),
    ]
