# Generated by Django 3.0.4 on 2020-04-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200423_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
