# Generated by Django 3.0.4 on 2020-04-23 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_auto_20200423_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_title', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('picture_path', models.URLField(max_length=500, null=True)),
                ('detail', models.TextField()),
                ('request_status', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Datetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('finish_time', models.DateTimeField(auto_now=True)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Request')),
            ],
        ),
        migrations.CreateModel(
            name='Request_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Request')),
            ],
        ),
    ]
