# Generated by Django 3.0.4 on 2020-04-23 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_request_request_contact_request_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_account',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
