# Generated by Django 3.0.4 on 2020-04-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200424_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_datetime',
            name='finish_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request_datetime',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
