# Generated by Django 3.0.2 on 2020-04-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200424_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('detail', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Audience_suggestion',
        ),
        migrations.DeleteModel(
            name='Member_suggestion',
        ),
    ]
