# Generated by Django 3.0.4 on 2020-04-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200425_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='picture_path',
            field=models.FileField(upload_to='activities'),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='picture_path',
            field=models.FileField(upload_to='user'),
        ),
    ]
