# Generated by Django 3.0.4 on 2020-04-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_equipment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='pass_code',
            field=models.CharField(default=12345, max_length=5),
            preserve_default=False,
        ),
    ]
